# Generated by Django 4.0.5 on 2022-06-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardapp', '0005_alter_review_content_alter_review_design_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.PositiveSmallIntegerField(choices=[(1, '1-Ok'), (2, '2-Scrollable'), (3, '3-Good'), (4, '4-Very Good'), (5, '5-Perfect'), (6, '6-Master Piece')], default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='design',
            field=models.PositiveSmallIntegerField(choices=[(1, '1-Ok'), (2, '2-Scrollable'), (3, '3-Good'), (4, '4-Very Good'), (5, '5-Perfect'), (6, '6-Master Piece')], default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='usability',
            field=models.PositiveSmallIntegerField(choices=[(1, '1-Ok'), (2, '2-Scrollable'), (3, '3-Good'), (4, '4-Very Good'), (5, '5-Perfect'), (6, '6-Master Piece')], default=0),
        ),
    ]
